// Code generated by protoc-gen-go. DO NOT EDIT.
// source: noun/noun.proto

package noun // import "github.com/marthjod/binquiry-experimental/noun"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _case "github.com/marthjod/binquiry-experimental/case"
import gender "github.com/marthjod/binquiry-experimental/gender"
import number "github.com/marthjod/binquiry-experimental/number"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CaseForm struct {
	Form                 string        `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	Number               number.Number `protobuf:"varint,2,opt,name=number,proto3,enum=number.Number" json:"number,omitempty"`
	Case                 _case.Case    `protobuf:"varint,3,opt,name=case,proto3,enum=case.Case" json:"case,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CaseForm) Reset()         { *m = CaseForm{} }
func (m *CaseForm) String() string { return proto.CompactTextString(m) }
func (*CaseForm) ProtoMessage()    {}
func (*CaseForm) Descriptor() ([]byte, []int) {
	return fileDescriptor_noun_7ae4e610768f119c, []int{0}
}
func (m *CaseForm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseForm.Unmarshal(m, b)
}
func (m *CaseForm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseForm.Marshal(b, m, deterministic)
}
func (dst *CaseForm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseForm.Merge(dst, src)
}
func (m *CaseForm) XXX_Size() int {
	return xxx_messageInfo_CaseForm.Size(m)
}
func (m *CaseForm) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseForm.DiscardUnknown(m)
}

var xxx_messageInfo_CaseForm proto.InternalMessageInfo

func (m *CaseForm) GetForm() string {
	if m != nil {
		return m.Form
	}
	return ""
}

func (m *CaseForm) GetNumber() number.Number {
	if m != nil {
		return m.Number
	}
	return number.Number_Singular
}

func (m *CaseForm) GetCase() _case.Case {
	if m != nil {
		return m.Case
	}
	return _case.Case_Nominative
}

type Noun struct {
	Gender               gender.Gender `protobuf:"varint,1,opt,name=gender,proto3,enum=gender.Gender" json:"gender,omitempty"`
	Cases                []*CaseForm   `protobuf:"bytes,2,rep,name=cases,proto3" json:"cases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Noun) Reset()         { *m = Noun{} }
func (m *Noun) String() string { return proto.CompactTextString(m) }
func (*Noun) ProtoMessage()    {}
func (*Noun) Descriptor() ([]byte, []int) {
	return fileDescriptor_noun_7ae4e610768f119c, []int{1}
}
func (m *Noun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Noun.Unmarshal(m, b)
}
func (m *Noun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Noun.Marshal(b, m, deterministic)
}
func (dst *Noun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Noun.Merge(dst, src)
}
func (m *Noun) XXX_Size() int {
	return xxx_messageInfo_Noun.Size(m)
}
func (m *Noun) XXX_DiscardUnknown() {
	xxx_messageInfo_Noun.DiscardUnknown(m)
}

var xxx_messageInfo_Noun proto.InternalMessageInfo

func (m *Noun) GetGender() gender.Gender {
	if m != nil {
		return m.Gender
	}
	return gender.Gender_Masculine
}

func (m *Noun) GetCases() []*CaseForm {
	if m != nil {
		return m.Cases
	}
	return nil
}

type ParseRequest struct {
	Word                 []byte   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseRequest) Reset()         { *m = ParseRequest{} }
func (m *ParseRequest) String() string { return proto.CompactTextString(m) }
func (*ParseRequest) ProtoMessage()    {}
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noun_7ae4e610768f119c, []int{2}
}
func (m *ParseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseRequest.Unmarshal(m, b)
}
func (m *ParseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseRequest.Marshal(b, m, deterministic)
}
func (dst *ParseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseRequest.Merge(dst, src)
}
func (m *ParseRequest) XXX_Size() int {
	return xxx_messageInfo_ParseRequest.Size(m)
}
func (m *ParseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseRequest proto.InternalMessageInfo

func (m *ParseRequest) GetWord() []byte {
	if m != nil {
		return m.Word
	}
	return nil
}

type ParseResponse struct {
	Noun                 *Noun    `protobuf:"bytes,1,opt,name=noun,proto3" json:"noun,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseResponse) Reset()         { *m = ParseResponse{} }
func (m *ParseResponse) String() string { return proto.CompactTextString(m) }
func (*ParseResponse) ProtoMessage()    {}
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noun_7ae4e610768f119c, []int{3}
}
func (m *ParseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseResponse.Unmarshal(m, b)
}
func (m *ParseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseResponse.Marshal(b, m, deterministic)
}
func (dst *ParseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseResponse.Merge(dst, src)
}
func (m *ParseResponse) XXX_Size() int {
	return xxx_messageInfo_ParseResponse.Size(m)
}
func (m *ParseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParseResponse proto.InternalMessageInfo

func (m *ParseResponse) GetNoun() *Noun {
	if m != nil {
		return m.Noun
	}
	return nil
}

func init() {
	proto.RegisterType((*CaseForm)(nil), "noun.CaseForm")
	proto.RegisterType((*Noun)(nil), "noun.Noun")
	proto.RegisterType((*ParseRequest)(nil), "noun.ParseRequest")
	proto.RegisterType((*ParseResponse)(nil), "noun.ParseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NounParserClient is the client API for NounParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NounParserClient interface {
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
}

type nounParserClient struct {
	cc *grpc.ClientConn
}

func NewNounParserClient(cc *grpc.ClientConn) NounParserClient {
	return &nounParserClient{cc}
}

func (c *nounParserClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, "/noun.NounParser/Parse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NounParserServer is the server API for NounParser service.
type NounParserServer interface {
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
}

func RegisterNounParserServer(s *grpc.Server, srv NounParserServer) {
	s.RegisterService(&_NounParser_serviceDesc, srv)
}

func _NounParser_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NounParserServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noun.NounParser/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NounParserServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NounParser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "noun.NounParser",
	HandlerType: (*NounParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _NounParser_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noun/noun.proto",
}

func init() { proto.RegisterFile("noun/noun.proto", fileDescriptor_noun_7ae4e610768f119c) }

var fileDescriptor_noun_7ae4e610768f119c = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0x41, 0x4b, 0x33, 0x31,
	0x10, 0xfd, 0xda, 0x6e, 0xcb, 0xe7, 0xb4, 0xb6, 0x90, 0x5e, 0x96, 0x1e, 0xa4, 0x2c, 0x22, 0xbd,
	0xb8, 0x91, 0xf5, 0x0f, 0x88, 0x82, 0xde, 0x8a, 0x04, 0x4f, 0xde, 0x76, 0xdb, 0x69, 0xbb, 0x62,
	0x92, 0x36, 0xd9, 0xa0, 0xfe, 0x7b, 0x99, 0x49, 0x04, 0xbd, 0x64, 0x26, 0x6f, 0xde, 0xbc, 0xf7,
	0x42, 0x60, 0x66, 0x6c, 0x30, 0x92, 0x8e, 0xf2, 0xe8, 0x6c, 0x67, 0x45, 0x46, 0xfd, 0x62, 0xbe,
	0x47, 0xb3, 0x45, 0x27, 0x63, 0x89, 0xa3, 0xc5, 0x6c, 0x53, 0x7b, 0x94, 0x74, 0x24, 0x60, 0x6e,
	0x82, 0x6e, 0xd0, 0xc9, 0x58, 0x22, 0x58, 0xec, 0xe0, 0xff, 0x43, 0xed, 0xf1, 0xd1, 0x3a, 0x2d,
	0x04, 0x64, 0x3b, 0xeb, 0x74, 0xde, 0x5b, 0xf6, 0x56, 0x67, 0x8a, 0x7b, 0x71, 0x05, 0xa3, 0xc8,
	0xcf, 0xfb, 0xcb, 0xde, 0x6a, 0x5a, 0x4d, 0xcb, 0xb4, 0xbe, 0xe6, 0xa2, 0xd2, 0x54, 0x5c, 0x40,
	0x46, 0x56, 0xf9, 0x80, 0x59, 0x50, 0xb2, 0x2f, 0x29, 0x2b, 0xc6, 0x8b, 0x17, 0xc8, 0xd6, 0x36,
	0x18, 0xd2, 0x8b, 0x29, 0xd9, 0x85, 0xf4, 0x52, 0xe8, 0x27, 0x2e, 0x2a, 0x4d, 0xc5, 0x25, 0x0c,
	0x69, 0xcf, 0xe7, 0xfd, 0xe5, 0x60, 0x35, 0x26, 0x5b, 0x7a, 0xf4, 0x4f, 0x54, 0x15, 0x87, 0x45,
	0x01, 0x93, 0xe7, 0xda, 0x79, 0x54, 0x78, 0x0a, 0xe8, 0x3b, 0x7a, 0xc1, 0x87, 0x75, 0x5b, 0xd6,
	0x9e, 0x28, 0xee, 0x0b, 0x09, 0xe7, 0x89, 0xe3, 0x8f, 0xd6, 0x78, 0xa4, 0xa8, 0x24, 0xc6, 0xa4,
	0x71, 0x05, 0x51, 0x99, 0xc2, 0x29, 0xc6, 0xab, 0x3b, 0x00, 0xba, 0xf1, 0x92, 0x13, 0x15, 0x0c,
	0xb9, 0x13, 0x22, 0x12, 0x7f, 0xfb, 0x2d, 0xe6, 0x7f, 0xb0, 0xa8, 0x5f, 0xfc, 0xbb, 0xbf, 0x79,
	0x2d, 0xf7, 0x6d, 0x77, 0x08, 0x4d, 0xb9, 0xb1, 0x5a, 0xea, 0xda, 0x75, 0x87, 0x37, 0xbb, 0x95,
	0x4d, 0x6b, 0x4e, 0xa1, 0x75, 0x5f, 0xd7, 0xf8, 0x79, 0x44, 0xd7, 0x6a, 0x34, 0x5d, 0xfd, 0xce,
	0xbf, 0xd9, 0x8c, 0xf8, 0x37, 0x6e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x73, 0x00, 0xc8,
	0xe1, 0x01, 0x00, 0x00,
}
