{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "creationTimestamp": null,
        "labels": {
            "k8s-app": "frontend"
        },
        "name": "frontend",
        "selfLink": "/api/v1/namespaces/default/services/frontend"
    },
    "spec": {
        "externalTrafficPolicy": "Cluster",
        "ports": [
            {
                "name": "tcp-8000-8000-q4pp2",
                "nodePort": 31271,
                "port": 8000,
                "protocol": "TCP",
                "targetPort": 8000
            }
        ],
        "selector": {
            "k8s-app": "frontend"
        },
        "sessionAffinity": "None",
        "type": "LoadBalancer"
    },
    "status": {
        "loadBalancer": {}
    }
}
